import React from "react";
import { Link } from "react-router-dom";
import { BarChartOutlined, LineChartOutlined, PieChartOutlined, DollarOutlined } from "@ant-design/icons";

export default function TransportReports({ isTab = false }) {
  const reports = [
    { title: "Trip History & Tracking", icon: <BarChartOutlined className="text-indigo-500" />, desc: "Historical logs of all fleet trips", link: "/transport/reports/trip-history" },
    { title: "Transport Revenue", icon: <DollarOutlined className="text-green-500" />, desc: "Revenue generated by customer trips" },
    { title: "Trip Profitability", icon: <LineChartOutlined className="text-blue-500" />, desc: "Cost vs Revenue analysis per trip" },
    { title: "Fuel Consumption", icon: <BarChartOutlined className="text-orange-500" />, desc: "Fuel usage across fleet vehicles" },
    { title: "Vehicle Utilization", icon: <PieChartOutlined className="text-purple-500" />, desc: "Active vs Idle time for vehicles" },
    { title: "Driver Performance", icon: <BarChartOutlined className="text-teal-500" />, desc: "Driver ratings and incident reports" },
    { title: "Trip Delays & Issues", icon: <LineChartOutlined className="text-red-500" />, desc: "Analysis of route delays" },
  ];

  return (
    <div className="space-y-6">
      {!isTab && (
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-3">
              <Link
                to="/transport"
                className="btn btn-ghost btn-sm px-2 text-slate-500"
              >
                ← Back to Menu
              </Link>
              Transport Reports & Analytics
            </h1>
            <p className="text-sm mt-1 ml-11">Generate insights and KPIs for transport operations.</p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reports.map((report, idx) => (
          <div key={idx} className="card hover:shadow-lg transition-shadow cursor-pointer bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700" onClick={() => report.link ? window.location.href = report.link : null}>
            <div className="card-body p-6 flex flex-row items-center gap-4">
              <div className="text-4xl bg-slate-50 dark:bg-slate-900 p-3 rounded-full flex items-center justify-center">
                {report.icon}
              </div>
              <div>
                <h3 className="font-bold text-lg text-slate-800 dark:text-slate-200">{report.title}</h3>
                <p className="text-sm text-slate-500 mt-1">{report.desc}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
